#!/usr/bin/env bash

cd ./uploads || { echo "Failed to navigate to uploads directory"; exit 1; }

for file in kafOut.mp3 raOut.mp3 shiinOut.mp3 siinOut.mp3;
do
    if [ ! -f "$file" ]; then
        touch "$file"
    fi
done

echo "Successfully initialized audio files"